Catrobat\ApiBundle\Entity\Project:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            name: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }
