framework:
  serializer: { enable_annotations: true }
  translator: { fallback: en }
  secret:          '%env(APP_SECRET)%'
  form:            ~
  csrf_protection: ~
  validation:      { enabled: true, enable_annotations: true }
  default_locale:  '%env(LOCALE)%'
  session:
    handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler
  fragments:       ~
  assets:
    version_strategy: 'catrobat.versioning'