################## index ################## 

catroweb_index:
    path: /
    defaults: { _controller: "CatrowebBundle:Default:index" }

catroweb_index_locale:
    path: /{_locale}/
    defaults: { _controller: "CatrowebBundle:Default:index", _locale: en }
    requirements:
        _locale:  en|de    
        
################## featured ################## 

catroweb_featured:
    resource: "@CatrowebBundle/Controller/FeaturedProjectController.php"
    type:     annotation
 
################## project listings ################## 

catroweb_most_downloaded:
    path:      /most-downloaded.{_format}
    methods:  [GET]
    defaults:  { _controller: "CatrowebBundle:Project:mostDownloaded", _format: html }
    requirements:
      _format:  html|json

catroweb_most_viewed:
    path:      /most-viewed
    methods:  [GET]
    defaults:  { _controller: "CatrowebBundle:Project:mostViewed" }

catroweb_newest:
    path:      /newest
    methods:  [GET]
    defaults:  { _controller: "CatrowebBundle:Project:newest" }

################## project details ################## 

project_show:
    path:      /projects/{id}
    methods:  [GET]
    defaults:  { _controller: "CatrowebBundle:Project:show" }
    requirements:
      page:  \d+
