parameters:
      catrobat.webdir:                  "%kernel.root_dir%/../web/"
      catrobat.file.extract.dir:        "%kernel.root_dir%/../web/resources/extract/"
      catrobat.file.storage.dir:        "%kernel.root_dir%/../web/resources/projects/"
      catrobat.screenshot.dir:  "%catrobat.webdir%resources/screenshots/"
      catrobat.screenshot.path: "resources/screenshots/"
      catrobat.thumbnail.dir:   "%catrobat.webdir%resources/thumbnails/"
      catrobat.thumbnail.path:  "resources/thumbnails/"

services:
# =========================== Kernel Listener ===========================
      catrowebbundle.listener.request:
              class: Catrobat\CatrowebBundle\EventListener\RequestListener
              tags:
                  - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
                  
# =========================== Services ===========================
      catroweb.projectmanager:
            class: Catrobat\CatrowebBundle\Model\ProjectManager
            arguments: ["@catrobat.file.extractor","@catrobat.file.repository", "@catrobat.screenshot.repository", "@doctrine"]

      catroweb.usermanager:
            class: Catrobat\CatrowebBundle\Model\UserManager
            arguments: ["@security.encoder_factory","@fos_user.util.username_canonicalizer", "@fos_user.util.email_canonicalizer", "@fos_user.entity_manager","%fos_user.model.user.class%"]

      catrobat.file.extractor:
              class:        Catrobat\CatrowebBundle\Services\CatrobatFileExtractor
              arguments:    ["%catrobat.file.extract.dir%"]

      catrobat.file.repository:
              class:        Catrobat\CatrowebBundle\Services\ProjectFileRepository
              arguments:    ["%catrobat.file.storage.dir%"]

      catrobat.screenshot.repository:
              class:        Catrobat\CatrowebBundle\Services\ScreenshotRepository
              arguments:    ["%catrobat.screenshot.dir%","%catrobat.screenshot.path%","%catrobat.thumbnail.dir%","%catrobat.thumbnail.path%"]

      extractor:
              alias:        catrobat.file.extractor
      projectrepository:
              alias:        catrobat.file.repository
      screenshotrepository:
              alias:        catrobat.screenshot.repository

# =========================== TWIG ===========================
      catrobat.twig.project.assets:
              class: Catrobat\CatrowebBundle\Twig\ProjectAssetsExtension
              arguments: ["@screenshotrepository"]
              tags:
                  - { name: twig.extension }              