services:
      catroweb.file.validator:
            class: Catrobat\CatrowebBundle\Services\Validators\ExtractedFileValidator
            calls:
              - [addValidator, ["@catroweb.file.validator.name"]]
              - [addValidator, ["@catroweb.file.validator.description"]]

      catroweb.file.validator.name:
            class: Catrobat\CatrowebBundle\Services\Validators\NameValidator
            public: false

      catroweb.file.validator.description:
            class: Catrobat\CatrowebBundle\Services\Validators\DescriptionValidator
            public: false

            