services:
      catroweb.file.validator:
            class: Catrobat\CatrowebBundle\Services\Validators\ExtractedFileValidator
            calls:
              - [addValidator, ["@catroweb.file.validator.required"]]

      catroweb.file.validator.required:
            class: Catrobat\CatrowebBundle\Services\Validators\RequiredFieldsValidator
