parameters:
#    catrobat_admin.example.class: Catrobat\AdminBundle\Example

services:
#    catrobat_admin.example:
#        class: %catrobat_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
