parameters:
#    catrobat_admin.example.class: Catrobat\AdminBundle\Example

services:
      catrowebadmin.command.init:
              class: Catrobat\AdminBundle\Command\InitDirectoriesCommand
              arguments: ["@catrowebadmin.filesystem","%catrobat.file.storage.dir%"]
              calls:
                - [setProjectfileDirectory, ["%catrobat.file.storage.dir%"]]
                - [setExtractDirectory, ["%catrobat.file.extract.dir%"]]
                - [setScreenshotDirectory, ["%catrobat.screenshot.dir%"]]
                - [setThumbnailDirectory, ["%catrobat.thumbnail.dir%"]]
              tags:
                -  { name: console.command }

      catrowebadmin.command.import:
              class: Catrobat\AdminBundle\Command\ProjectImportCommand
              arguments: ["@catrowebadmin.filesystem","@catrobat.core.model.usermanager","@catrobat.core.model.projectmanager"]
              tags:
                -  { name: console.command }

      catrowebadmin.filesystem:
              class: Symfony\Component\Filesystem\Filesystem
              public: false
              