imports:
    - { resource: services.yml }
    
services:

    tokengenerator.inner:
              class:        Catrobat\CoreBundle\Services\TokenGenerator

    tokengenerator:
          class:  Catrobat\CoreBundle\Services\TestEnv\ProxyTokenGenerator
          arguments: ["@tokengenerator.inner"]


    time.inner:
              class:        Catrobat\CoreBundle\Services\Time

    time:
          class:  Catrobat\CoreBundle\Services\TestEnv\ProxyTime
          arguments: ["@time.inner"]