parameters:
      catrobat.webdir:                  "%kernel.root_dir%/../web/"
      catrobat.file.extract.dir:        "%kernel.root_dir%/../web/resources/extract/"
      catrobat.file.storage.dir:        "%kernel.root_dir%/../web/resources/projects/"
      catrobat.file.storage.path:        "resources/projects/"
      catrobat.screenshot.dir:  "%catrobat.webdir%resources/screenshots/"
      catrobat.screenshot.path: "resources/screenshots/"
      catrobat.thumbnail.dir:   "%catrobat.webdir%resources/thumbnails/"
      catrobat.thumbnail.path:  "resources/thumbnails/"

services:
      catrobat.core.model.projectmanager:
            class: Catrobat\CoreBundle\Model\ProjectManager
            arguments: ["@catrobat.core.services.file.extractor","@catrobat.core.services.file.repository", "@catrobat.core.services.screenshot.repository", "@doctrine","@catroweb.file.validator"]

      catrobat.core.model.usermanager:
            class: Catrobat\CoreBundle\Model\UserManager
            arguments: ["@security.encoder_factory","@fos_user.util.username_canonicalizer", "@fos_user.util.email_canonicalizer", "@fos_user.entity_manager","%fos_user.model.user.class%"]

      catrobat.core.services.file.extractor:
              class:        Catrobat\CoreBundle\Services\CatrobatFileExtractor
              arguments:    ["%catrobat.file.extract.dir%"]

      catrobat.core.services.file.repository:
              class:        Catrobat\CoreBundle\Services\ProjectFileRepository
              arguments:    ["%catrobat.file.storage.dir%","%catrobat.file.storage.path%"]

      catrobat.core.services.screenshot.repository:
              class:        Catrobat\CoreBundle\Services\ScreenshotRepository
              arguments:    ["%catrobat.screenshot.dir%","%catrobat.screenshot.path%","%catrobat.thumbnail.dir%","%catrobat.thumbnail.path%"]
              
      catrobat.core.services.tokengenerator:
              class:        Catrobat\CoreBundle\Services\TokenGenerator
