services:
      catroweb.file.validator:
            class: Catrobat\CoreBundle\Services\Validators\ExtractedFileValidator

      catroweb.file.validator.name:
            class: Catrobat\CoreBundle\Services\Validators\NameValidator
            public: false
            tags:
            -  { name: catroweb.file.validator.service }

      catroweb.file.validator.description:
            class: Catrobat\CoreBundle\Services\Validators\DescriptionValidator
            public: false
            tags:
            -  { name: catroweb.file.validator.service }

      catroweb.file.validator.filestructure:
            class: Catrobat\CoreBundle\Services\Validators\FileStructureValidator
            public: false
            tags:
            -  { name: catroweb.file.validator.service }

      catroweb.file.validator.definedimages:
            class: Catrobat\CoreBundle\Services\Validators\OnlyDefinedImagesValidator
            public: false
            tags:
            -  { name: catroweb.file.validator.service }
            