services:

      catrowebadmin.block.programs.all:
        class: Catrobat\AppBundle\Admin\AllProgramsAdmin
        tags:
          - { name: sonata.admin, manager_type: orm, group: Programs, label: All Programs }
        arguments: [null, Catrobat\AppBundle\Entity\Program, null]

      catrowebadmin.block.programs.approve:
        class: Catrobat\AppBundle\Admin\ApproveProgramsAdmin
        tags:
          - { name: sonata.admin, manager_type: orm, group: Programs, label: Approve Programs }
        arguments: [null, Catrobat\AppBundle\Entity\Program, null]

      catrowebadmin.block.programs.reported:
        class: Catrobat\AppBundle\Admin\ReportedProgramsAdmin
        tags:
          - { name: sonata.admin, manager_type: orm, group: Programs, label: Reported Programs }
        arguments: [null, Catrobat\AppBundle\Entity\ProgramInappropriateReport, null]

      catrowebadmin.block.tools.notify:
        class: Catrobat\AppBundle\Admin\UploadNotificationAdmin
        tags:
          - { name: sonata.admin, manager_type: orm, group: Tools, label: Notifications }
        arguments: [null, Catrobat\AppBundle\Entity\Notification, null]

      catrowebadmin.block.featured.program:
        class: Catrobat\AppBundle\Admin\FeaturedProgramAdmin
        tags:
          - { name: sonata.admin, manager_type: orm, group: Featured, label: Programs }
        arguments: [null, Catrobat\AppBundle\Entity\FeaturedProgram, null]

      catrowebadmin.block.featured.url:
        class: Catrobat\AppBundle\Admin\FeaturedUrlAdmin
        tags:
          - { name: sonata.admin, manager_type: orm, group: Featured, label: Urls }
        arguments: [null, Catrobat\AppBundle\Entity\FeaturedProgram, null]

      catrowebadmin.block.categoriesadmin:
              class: Catrobat\AppBundle\Admin\CategoriesAdmin
              tags:
                - { name: sonata.admin, manager_type: orm, group: Programs, label: Categories }
              arguments: [null, Catrobat\AppBundle\Entity\StarterCategory, null]
        