services:

      catrowebadmin.block.all_programs:
        class: AppBundle\Admin\AllProgramsAdmin
        tags:
          - { name: sonata.admin, manager_type: orm, group: Programs, label: All Programs }
        arguments: [null, Catrobat\CoreBundle\Entity\Program, null]

      catrowebadmin.block.approve_programs:
        class: AppBundle\Admin\ApproveProgramsAdmin
        tags:
          - { name: sonata.admin, manager_type: orm, group: Programs, label: Approve Programs }
        arguments: [null, Catrobat\CoreBundle\Entity\Program, null]

      catrowebadmin.block.notify_upload_programs:
        class: AppBundle\Admin\UploadNotificationAdmin
        tags:
          - { name: sonata.admin, manager_type: orm, group: Tools, label: Upload Notify }
        arguments: [null, Catrobat\CoreBundle\Entity\User, null]
