services:
      catrowebadmin.filesystem:
              class: Symfony\Component\Filesystem\Filesystem
              public: false

      catrowebadmin.command.init:
              class: Catrobat\AppBundle\Commands\InitDirectoriesCommand
              arguments: ["@catrowebadmin.filesystem","%catrobat.file.storage.dir%"]
              calls:
                - [setProgramfileDirectory, ["%catrobat.file.storage.dir%"]]
                - [setExtractDirectory, ["%catrobat.file.extract.dir%"]]
                - [setScreenshotDirectory, ["%catrobat.screenshot.dir%"]]
                - [setThumbnailDirectory, ["%catrobat.thumbnail.dir%"]]
              tags:
                -  { name: console.command }

      catrowebadmin.command.import:
              class: Catrobat\AppBundle\Commands\ProgramImportCommand
              arguments: ["@catrowebadmin.filesystem","@usermanager","@programmanager"]
              tags:
                -  { name: console.command }

      catrowebadmin.command.refresh:
              class: Catrobat\AppBundle\Commands\RefreshCommand
              arguments: ["@catrowebadmin.filesystem"]
              tags:
                -  { name: console.command }

      command.reset:
              class: Catrobat\AppBundle\Commands\ResetCommand
              tags:
                -  { name: console.command }