imports:
    - { resource: config_dev.yml }
    - { resource: services_test.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        enabled: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

doctrine:
    dbal:
        driver: pdo_sqlite
        path: sqlite/behattest.sqlite

parameters:
      catrobat.file.extract.dir: "%kernel.root_dir%/../web/resources_test/extract/"
      catrobat.file.storage.dir: "%kernel.root_dir%/../web/resources_test/projects/"
      catrobat.screenshot.dir:   "%catrobat.webdir%resources_test/screenshots/"
      catrobat.screenshot.path:  "resources_test/screenshots/"
      catrobat.thumbnail.dir:    "%catrobat.webdir%resources_test/thumbnails/"
      catrobat.thumbnail.path:   "resources_test/thumbnails/"

monolog:
    channels: ["upload"]
    handlers:
        upload:
            type: stream
            path: "%kernel.logs_dir%/upload.log"
            channels: [upload]
        main:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug