imports:
    - { resource: config_dev.yml }
    - { resource: services_test.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        enabled: true
        collect: true

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
    logging: true

doctrine:
    dbal:
        driver: pdo_sqlite
        path: "%kernel.root_dir%/../sqlite/behattest.sqlite"

parameters:
      catrobat.file.extract.dir:   "%catrobat.webdir%resources_test/extract/"
      catrobat.file.storage.dir:   "%catrobat.webdir%resources_test/projects/"
      catrobat.screenshot.dir:     "%catrobat.webdir%resources_test/screenshots/"
      catrobat.screenshot.path:    "resources_test/screenshots/"
      catrobat.thumbnail.dir:      "%catrobat.webdir%resources_test/thumbnails/"
      catrobat.thumbnail.path:     "resources_test/thumbnails/"
      catrobat.featuredimage.dir:  "%catrobat.webdir%resources_test/featured/"
      catrobat.featuredimage.path: "resources_test/featured/"
      catrobat.apk.dir:            "%catrobat.webdir%resources_test/apk/"
      catrobat.mediapackage.dir:   "%catrobat.webdir%resources_test/mediapackage/"
      catrobat.mediapackage.path:  "resources_test/mediapackage/"
      catrobat.backup.dir:         "%catrobat.webdir%resources_test/backups/"
      catrobat.snapshot.dir:         "%catrobat.webdir%resources_test/snapshots/"

monolog:
    channels: ["upload"]
    handlers:
        upload:
            type: stream
            path: "%kernel.logs_dir%/upload.log"
            channels: [upload]
        main:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            
security:
    firewalls:
        main: 
            http_basic: ~