services:
      catroweb.file.validator.name:
            class: Catrobat\AppBundle\Listeners\NameValidator
            arguments:    ["@rudewordfilter"]
            tags:
            - { name: kernel.event_listener, event: catrobat.program.before, method: onProgramBeforeInsert }

      catroweb.file.validator.description:
            class: Catrobat\AppBundle\Listeners\DescriptionValidator
            arguments:    ["@rudewordfilter"]
            tags:
            - { name: kernel.event_listener, event: catrobat.program.before, method: onProgramBeforeInsert }

      catroweb.file.validator.filestructure:
            class: Catrobat\AppBundle\Listeners\FileStructureValidator
            tags:
            - { name: kernel.event_listener, event: catrobat.program.before, method: onProgramBeforeInsert, priority: 250 }

      catroweb.file.validator.definedimages:
            class: Catrobat\AppBundle\Listeners\OnlyDefinedImagesValidator
            tags:
            - { name: kernel.event_listener, event: catrobat.program.before, method: onProgramBeforeInsert }

      catroweb.file.validator.xmlheadervalidator:
            class: Catrobat\AppBundle\Listeners\ProgramXmlHeaderValidator
            tags:
            - { name: kernel.event_listener, event: catrobat.program.before, method: onProgramBeforeInsert }

      catroweb.file.license.updater:
            class: Catrobat\AppBundle\Listeners\LicenseUpdater
            tags:
            - { name: kernel.event_listener, event: catrobat.program.before, method: onProgramBeforeInsert, priority: -1 }

      catroweb.file.remix.updater:
            class: Catrobat\AppBundle\Listeners\RemixUpdater
            arguments: ["@programrepository"]
            tags:
            - { name: kernel.event_listener, event: catrobat.program.after.insert, method: onProgramAfterInsert }
            
      catrobat.core.services.invalidprogramuploadlogger:
              class:        Catrobat\AppBundle\Listeners\InvalidProgramUploadLogger
              arguments:    ["@logger"]
              tags:
                  - { name: monolog.logger, channel: upload }
                  - { name: kernel.event_listener, event: catrobat.program.invalid.upload, method: onInvalidProgramUploadedEvent }
