services:
      catroweb.file.validator.name:
            class: AppBundle\Listeners\NameValidator
            arguments:    ["@rudewordfilter"]
            tags:
            - { name: kernel.event_listener, event: catrobat.program.before, method: onProgramBeforeInsert }

      catroweb.file.validator.description:
            class: AppBundle\Listeners\DescriptionValidator
            arguments:    ["@rudewordfilter"]
            tags:
            - { name: kernel.event_listener, event: catrobat.program.before, method: onProgramBeforeInsert }

      catroweb.file.validator.filestructure:
            class: AppBundle\Listeners\FileStructureValidator
            tags:
            - { name: kernel.event_listener, event: catrobat.program.before, method: onProgramBeforeInsert, priority: 250 }

      catroweb.file.validator.definedimages:
            class: AppBundle\Listeners\OnlyDefinedImagesValidator
            tags:
            - { name: kernel.event_listener, event: catrobat.program.before, method: onProgramBeforeInsert }

      catroweb.file.validator.xmlheadervalidator:
            class: AppBundle\Listeners\ProgramXmlHeaderValidator
            tags:
            - { name: kernel.event_listener, event: catrobat.program.before, method: onProgramBeforeInsert }
            
      catrobat.core.services.invalidprogramuploadlogger:
              class:        AppBundle\Listeners\InvalidProgramUploadLogger
              arguments:    ["@logger"]
              tags:
                  - { name: monolog.logger, channel: upload }
                  - { name: kernel.event_listener, event: catrobat.program.invalid.upload, method: onInvalidProgramUploadedEvent }
