parameters:
     catrobat.test.directory.source: "%kernel.root_dir%/../testdata/DataFixtures/test.catrobat"
     catrobat.test.directory.target: "%kernel.root_dir%/../testdata/DataFixtures/GeneratedFixtures/"
      
services:
    catrobat.test.command.generatetestdata:
        class: Catrobat\AppBundle\Commands\GenerateTestDataCommand
        arguments: ["@catrobat.test.filesystem", "@catrobat.test.extractor", "@catrobat.test.compressor", "%catrobat.test.directory.source%","%catrobat.test.directory.target%"]
        tags:
            -  { name: console.command }

    catrobat.test.filesystem:
        class: Symfony\Component\Filesystem\Filesystem
        public: false

    catrobat.test.extractor:
        class: Catrobat\AppBundle\Services\CatrobatFileExtractor
        arguments: ["%catrobat.test.directory.target%","%catrobat.file.extract.path%"]

    catrobat.test.compressor:
        class: Catrobat\AppBundle\Services\CatrobatFileCompressor

    tokengenerator.inner:
        class: Catrobat\AppBundle\Services\TokenGenerator

    tokengenerator:
        class: Catrobat\AppBundle\Services\TestEnv\ProxyTokenGenerator
        arguments: ["@tokengenerator.inner"]

    time.inner:
        class:        Catrobat\AppBundle\Services\Time

    time:
        class:  Catrobat\AppBundle\Services\TestEnv\ProxyTime
        arguments: ["@time.inner"]