parameters:
      catrobat.webdir:                  "%kernel.root_dir%/../web/"
      catrobat.file.extract.dir:        "%kernel.root_dir%/../web/resources/extract/"
      catrobat.file.storage.dir:        "%kernel.root_dir%/../web/resources/programs/"
      catrobat.file.storage.path:        "resources/programs/"
      catrobat.screenshot.dir:  "%catrobat.webdir%resources/screenshots/"
      catrobat.screenshot.path: "resources/screenshots/"
      catrobat.thumbnail.dir:   "%catrobat.webdir%resources/thumbnails/"
      catrobat.thumbnail.path:  "resources/thumbnails/"
      
services:

# =========================== Kernel Listener ===========================
    catrowebbundle.listener.request:
        class: Catrobat\AppBundle\Listeners\LanguageListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
                  
    apikey_authenticator:
        class:     Catrobat\AppBundle\Security\ApiKeyAuthenticator
        arguments: ["@fos_user.user_provider.username","@translator"]

    programrepository:
        class: CoreBundle\Entity\ProgramRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - "AppBundle:Program"

    rudewordrepository:
        class: CoreBundle\Entity\RudeWordsRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - "AppBundle:RudeWord"

    programmanager:
        class: Catrobat\AppBundle\Model\ProgramManager
        arguments: 
            - "@fileextractor"
            - "@filerepository"
            - "@screenshotrepository"
            - "@doctrine.orm.entity_manager"
            - "@programrepository"
            - "@event_dispatcher"
        tags:
            -  { name:  "knp_paginator.injectable" }

    rudewordfilter:
        class: Catrobat\AppBundle\Services\RudeWordFilter
        arguments: ["@rudewordrepository"]

    usermanager:
        class: Catrobat\AppBundle\Model\UserManager
        arguments: ["@security.encoder_factory","@fos_user.util.username_canonicalizer", "@fos_user.util.email_canonicalizer", "@fos_user.entity_manager","%fos_user.model.user.class%"]

    fileextractor:
        class: Catrobat\AppBundle\Services\CatrobatFileExtractor
        arguments: ["%catrobat.file.extract.dir%"]

    filecompressor:
        class: Catrobat\AppBundle\Services\CatrobatFileCompressor

    filerepository:
        class: Catrobat\AppBundle\Services\ProgramFileRepository
        arguments: ["%catrobat.file.storage.dir%","%catrobat.file.storage.path%", "@filecompressor"]

    screenshotrepository:
        class: Catrobat\AppBundle\Services\ScreenshotRepository
        arguments: ["%catrobat.screenshot.dir%","%catrobat.screenshot.path%","%catrobat.thumbnail.dir%","%catrobat.thumbnail.path%"]
              
    tokengenerator:
        class: Catrobat\AppBundle\Services\TokenGenerator

    time:
        class: Catrobat\AppBundle\Services\Time

    elapsedtime:
        class: Catrobat\AppBundle\Services\ElapsedTimeString
        arguments: ["@translator","@time"]
