version: '3.7'

services:

  # APACHE WITH PHP
  app.catroweb:
    build:
      args:
        - APP_ENVIRONMENT=dev
      context: ../
      dockerfile: docker/Dockerfile
    container_name: app.catroweb
    image: app.catroweb
    command: ["sh", "/var/www/catroweb/docker/app/startup.sh"]
    depends_on:
      - db.catroweb.dev
      - db.catroweb.test
      - chrome.catroweb
    ports:
      - 8080:80

  db.catroweb.dev:
    image: mariadb:10.3.11
    container_name: db.catroweb.dev
    ports:
      - 3306
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=catroweb_dev


  # --- Tests:

  chrome.catroweb:
    image: zenika/alpine-chrome
    container_name: chrome.catroweb
    restart: on-failure
    volumes:
      - ./../tests/testdata/DataFixtures:/var/www/catroweb/tests/testdata/DataFixtures:ro
    command: ["chromium-browser", "--headless", "--disable-gpu", "--no-sandbox", "--remote-debugging-address=0.0.0.0", "--remote-debugging-port=9222"]
    ports:
      - 9222

  db.catroweb.test:
    image: mariadb:10.3.11
    container_name: db.catroweb.test
    ports:
      - 3306
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=catroweb_test


  # --- Tools:

  phpmyadmin.catroweb.dev:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin.catroweb.dev
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8081:80
    volumes:
      - /sessions
    external_links:
      - db.catroweb.dev:db
      - db.catroweb.test:db
    depends_on:
      - db.catroweb.dev
      - db.catroweb.test
