################## index ################## 

catroweb_index:
    path: /
    defaults: { _controller: "catrobat.web.program.controller:indexAction" }

catroweb_index_locale:
    path: /{_locale}/
    defaults: { _controller: "catrobat.web.program.controller:indexAction", _locale: en }
    requirements:
        _locale:  en|de    
        
################## featured ################## 

#catroweb_featured:
#    resource: "@CatrobatWebBundle/Controller/FeaturedProjectController.php"
#    type:     annotation

################## program listings ################## 

#catroweb_most_downloaded:
#    path:      /most_downloaded.{_format}
#    methods:  [GET]
#    defaults:  { _controller: "catrobat.web.project.controller:mostDownloadedAction", _format: json }
#    requirements:
#      _format:  json

#catroweb_most_viewed:
#    path:      /most-viewed.{_format}
#    methods:  [GET]
#    defaults:  { _controller: "catrobat.web.project.controller:mostViewedAction", _format: html }
#    requirements:
#          _format:  html|json
#
#catroweb_newest:
#    path:      /newest.{_format}
#    methods:  [GET]
#    defaults:  { _controller: "catrobat.web.project.controller:newestAction", _format: html }
#    requirements:
#          _format:  html|json


################## program details ################## 

program_show:
    path:      /programs/{id}
    methods:  [GET]
    defaults:  { _controller: "catrobat.web.program.controller:showAction" }
    requirements:
      page:  \d+
