################## index ################## 

catroweb_index:
    path: /
    defaults: { _controller: "catrobat.web.program.controller:indexAction" }

catroweb_index_locale:
    path: /{_locale}/
    defaults: { _controller: "catrobat.web.program.controller:indexAction", _locale: en }
    requirements:
        _locale:  en|de    
        
################## featured ################## 

catroweb_featured:
    resource: "@CatrobatWebBundle/Controller/FeaturedProgramController.php"
    type:     annotation
 
################## program listings ################## 

catroweb_most_downloaded:
    path:      /most-downloaded.{_format}
    methods:  [GET]
    defaults:  { _controller: "catrobat.web.program.controller:mostDownloadedAction", _format: html }
    requirements:
      _format:  html|json

catroweb_most_viewed:
    path:      /most-viewed
    methods:  [GET]
    defaults:  { _controller: "catrobat.web.program.controller:mostViewedAction" }

catroweb_newest:
    path:      /newest
    methods:  [GET]
    defaults:  { _controller: "catrobat.web.program.controller:newestAction" }

################## program details ################## 

program_show:
    path:      /programs/{id}
    methods:  [GET]
    defaults:  { _controller: "catrobat.web.program.controller:showAction" }
    requirements:
      page:  \d+
