################## index ################## 

catroweb_index:
    path: /
    defaults: { _controller: "catrobat.web.program.controller:indexAction" }

catroweb_index_locale:
    path: /{_locale}/
    defaults: { _controller: "catrobat.web.program.controller:indexAction", _locale: en }
    requirements:
        _locale:  en|de    
        
################## featured ################## 

#catroweb_featured:
#    resource: "@CatrobatWebBundle/Controller/FeaturedProjectController.php"
#    type:     annotation

################## program details ##################
program_show:
    path:      /programs/{id}
    methods:  [GET]
    defaults:  { _controller: "catrobat.web.program.controller:showAction" }
    requirements:
      page:  \d+

# Same as /programs ... just for compatibility reason again with /details
detail_show:
    path:      /details/{id}
    methods:  [GET]
    defaults:  { _controller: "catrobat.web.program.controller:showAction" }
    requirements:
      page:  \d+
