################## index ################## 

catroweb_index:
    path: /
    defaults: { _controller: "catrobat.web.project.controller:indexAction" }

catroweb_index_locale:
    path: /{_locale}/
    defaults: { _controller: "catrobat.web.project.controller:indexAction", _locale: en }
    requirements:
        _locale:  en|de    
        
################## featured ################## 

catroweb_featured:
    resource: "@CatrobatWebBundle/Controller/FeaturedProjectController.php"
    type:     annotation
 
################## project listings ################## 

catroweb_most_downloaded:
    path:      /most_downloaded.{_format}
    methods:  [GET]
    defaults:  { _controller: "catrobat.web.project.controller:mostDownloadedAction", _format: json }
    requirements:
      _format:  json

#catroweb_most_viewed:
#    path:      /most-viewed.{_format}
#    methods:  [GET]
#    defaults:  { _controller: "catrobat.web.project.controller:mostViewedAction", _format: html }
#    requirements:
#          _format:  html|json
#
#catroweb_newest:
#    path:      /newest.{_format}
#    methods:  [GET]
#    defaults:  { _controller: "catrobat.web.project.controller:newestAction", _format: html }
#    requirements:
#          _format:  html|json

################## project details ################## 

project_show:
    path:      /projects/{id}
    methods:  [GET]
    defaults:  { _controller: "catrobat.web.project.controller:showAction" }
    requirements:
      page:  \d+
