parameters:
      catrobat.web.program.controller.class: Catrobat\WebBundle\Controller\ProgramController

services:
# =========================== Kernel Listener ===========================
      catrowebbundle.listener.request:
              class: Catrobat\WebBundle\EventListener\LanguageListener
              tags:
                  - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

# =========================== Controller ===========================

      catrobat.web.program.controller:
              class: "%catrobat.web.program.controller.class%"
              arguments: ["@templating", "@catrobat.core.model.programmanager"]

              
# =========================== TWIG ===========================
      catrobat.twig.program.assets:
              class: Catrobat\WebBundle\Twig\ProgramAssetsExtension
              arguments: ["@catrobat.core.services.screenshot.repository"]
              tags:
                  - { name: twig.extension }              