parameters:
      catrobat.web.default.controller.class: Catrobat\WebBundle\Controller\DefaultController
      catrobat.web.tutorial.controller.class: Catrobat\WebBundle\Controller\TutorialController

services:


# =========================== Controller ===========================
      catrobat.web.default.controller:
                          class: "%catrobat.web.default.controller.class%"
                          arguments: ["@templating", "@programmanager"]

      catrobat.web.tutorial.controller:
              class: "%catrobat.web.tutorial.controller.class%"
              arguments: ["@templating"]

              

