parameters:
      catrobat.test.directory.source: "%kernel.root_dir%/../src/Catrobat/TestBundle/DataFixtures/compass.catrobat"
      catrobat.test.directory.target: "%kernel.root_dir%/../src/Catrobat/TestBundle/DataFixtures/GeneratedFixtures/"
      
services:
      catrobat.test.command.generatetestdata:
              class: Catrobat\TestBundle\Command\GenerateTestDataCommand
              arguments: ["@catrobat.test.filesystem", "@catrobat.test.extractor", "@catrobat.test.compressor", "%catrobat.test.directory.source%","%catrobat.test.directory.target%"]
              tags:
                -  { name: console.command }

      catrobat.test.filesystem:
              class: Symfony\Component\Filesystem\Filesystem
              public: false
              
      catrobat.test.extractor:
              class:        Catrobat\CoreBundle\Services\CatrobatFileExtractor
              arguments:    ["%catrobat.test.directory.target%"]
  
      catrobat.test.compressor:
              class:        Catrobat\CoreBundle\Services\CatrobatFileCompressor
              arguments:    ["%catrobat.test.directory.target%"]
             