catrobat_api_check_token:
    pattern:  /api/checkToken/check.json
    methods: [POST]
    defaults: { _controller: 'CatrobatApiBundle:Api:checkToken', _format: json }

catrobat_api_upload:
    pattern:  /api/upload.{_format}
    defaults: { _controller: 'CatrobatApiBundle:Api:upload', _format: html}
