catrobat_api_check_token:
    pattern:  /api/checkToken/check.json
    methods: [POST]
    defaults: { _controller: 'catrobat.api.controller:checkTokenAction', _format: json }

catrobat_api_login_or_register:
    pattern:  /api/loginOrRegister/loginOrRegister.json
    methods: [POST, GET]
    defaults: { _controller: 'catrobat.api.controller:loginOrRegisterAction', _format: json }

catrobat_api_upload:
    pattern:  /api/upload.{_format}
    defaults: { _controller: 'catrobat.api.controller:uploadAction', _format: html}
