parameters:
    catrobat.api.controller.search.class: Catrobat\ApiBundle\Controller\SearchController
    catrobat.api.controller.upload.class: Catrobat\ApiBundle\Controller\UploadController
    catrobat.api.controller.security.class: Catrobat\ApiBundle\Controller\SecurityController
    catrobat.api.controller.listprograms.class: Catrobat\ApiBundle\Controller\ListProgramsController

services:
    catrobat.api.controller.search:
        class: "%catrobat.api.controller.search.class%"
        arguments: ["@templating", "@catrobat.core.model.programmanager"]

    catrobat.api.controller.listprograms:
        class: "%catrobat.api.controller.listprograms.class%"
        arguments: ["@templating", "@catrobat.core.model.programmanager"]

    catrobat.api.controller.listmostdownloadedprograms:
        class: "%catrobat.api.controller.listprograms.class%"
        arguments: ["@templating", "@catrobat.core.model.programmanager"]

    catrobat.api.controller.listmostviewedprograms:
        class: "%catrobat.api.controller.listprograms.class%"
        arguments: ["@templating", "@catrobat.core.model.programmanager"]

    catrobat.api.controller.security:
        class: "%catrobat.api.controller.security.class%"
        arguments: ["@templating","@catrobat.core.model.usermanager", "@catrobat.core.services.tokengenerator"]
        
    catrobat.api.controller.upload:
        class: "%catrobat.api.controller.upload.class%"
        arguments: ["@templating","@catrobat.core.model.usermanager", "@security.context", "@catrobat.core.model.programmanager", "@catrobat.core.services.tokengenerator"]

    uploadtoken.security.authentication.provider:
        class:  Catrobat\ApiBundle\Security\UploadTokenAuthenticationProvider
        arguments: [""]

    uploadtoken.security.authentication.listener:
        class:  Catrobat\ApiBundle\Security\UploadTokenListener
        arguments: ["@security.context", "@security.authentication.manager","","@templating"]
