parameters:
    catrobat.api.controller.class: Catrobat\ApiBundle\Controller\ApiController

services:
    catrobat.api.controller:
        class: "%catrobat.api.controller.class%"
        arguments: ["@templating","@catroweb.usermanager","@validator","@security.context", "@catroweb.projectmanager"]

    uploadtoken.security.authentication.provider:
        class:  Catrobat\ApiBundle\Security\UploadTokenAuthenticationProvider
        arguments: [""]

    uploadtoken.security.authentication.listener:
        class:  Catrobat\ApiBundle\Security\UploadTokenListener
        arguments: ["@security.context", "@security.authentication.manager","","@templating"]
