parameters:
#    catrobat_api.example.class: Catrobat\ApiBundle\Example

services:
    uploadtoken.security.authentication.provider:
        class:  Catrobat\ApiBundle\Security\UploadTokenAuthenticationProvider
        arguments: [""]

    uploadtoken.security.authentication.listener:
        class:  Catrobat\ApiBundle\Security\UploadTokenListener
        arguments: ["@security.context", "@security.authentication.manager","","@templating"]
