parameters:
#    catrobat_api.example.class: Catrobat\ApiBundle\Example

services:
#    catrobat_api.example:
#        class: %catrobat_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
